start-backup-from-icloud-photos: ## Start backup from iCloud Photos
	@echo "Starting backup from iCloud Photos"
	$(PYTHON) -m src.entry.functions.start_backup_from_icloud_photos \
		--origin $(TARGET_ORIGIN) \
		--destination $(TARGET_DESTINATION) \
		--log-level info
	@echo "Backup from iCloud Photos started"