
services:
  rabbitmq:
    image: rabbitmq.app
    hostname: rabbitmq 
    container_name: ${RABBITMQ_CONTAINER_NAME:-local.rabbitmq.container}

    # Port mapping: <host>:<port_over_container>
    # 5672: Port AMQP 
    # 15672: Port 
    # 4369, 25672: Ports
    ports:
      - "5672:5672"
      - "15672:15672"
      - "4369:4369" # For clustering, 
      - "25672:25672" # For clustering, 

    environment:      
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest} 
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    env_file:
      - .env 

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
      - rabbitmq_logs:/var/log/rabbitmq 

    restart: always

# Definição dos volumes nomeados
volumes:
  rabbitmq_data:
  rabbitmq_logs:
